// Tile type constants and visual configuration
export const TILE_TYPES = {
    EMPTY: 0,
    FLOOR: 1,
    WALL: 2,
    DOOR: 3,
    WATER: 4,
    CHEST: 5,
    TORCH: 6,
    STAIRS: 7,
    LAVA: 8,
    GRASS: 9,
};

export const TILE_LABELS = {
    [TILE_TYPES.EMPTY]: 'Empty',
    [TILE_TYPES.FLOOR]: 'Floor',
    [TILE_TYPES.WALL]: 'Wall',
    [TILE_TYPES.DOOR]: 'Door',
    [TILE_TYPES.WATER]: 'Water',
    [TILE_TYPES.CHEST]: 'Chest',
    [TILE_TYPES.TORCH]: 'Torch',
    [TILE_TYPES.STAIRS]: 'Stairs',
    [TILE_TYPES.LAVA]: 'Lava',
    [TILE_TYPES.GRASS]: 'Grass',
};

export const TILE_ICONS = {
    [TILE_TYPES.EMPTY]: '⬛',
    [TILE_TYPES.FLOOR]: '🟫',
    [TILE_TYPES.WALL]: '🧱',
    [TILE_TYPES.DOOR]: '🚪',
    [TILE_TYPES.WATER]: '💧',
    [TILE_TYPES.CHEST]: '📦',
    [TILE_TYPES.TORCH]: '🔥',
    [TILE_TYPES.STAIRS]: '🪜',
    [TILE_TYPES.LAVA]: '🌋',
    [TILE_TYPES.GRASS]: '🌿',
};

// Theme color palettes
export const THEMES = {
    dungeon: {
        name: 'Dark Dungeon',
        floor: '#3a3535',
        wall: '#1a1616',
        wallTop: '#252020',
        door: '#6b4226',
        accent: '#8b5e3c',
        ambient: '#1a0a2e',
        fog: '#0a0510',
    },
    cave: {
        name: 'Crystal Cave',
        floor: '#2d2d3d',
        wall: '#1a1a2e',
        wallTop: '#22223a',
        door: '#4a6fa5',
        accent: '#6ec6ff',
        ambient: '#0e0e2e',
        fog: '#05051a',
    },
    forest: {
        name: 'Enchanted Forest',
        floor: '#2d4a2d',
        wall: '#1a331a',
        wallTop: '#264026',
        door: '#8b6914',
        accent: '#4caf50',
        ambient: '#0a1a0a',
        fog: '#050f05',
    },
    tavern: {
        name: 'Cozy Tavern',
        floor: '#5c4033',
        wall: '#3e2a1e',
        wallTop: '#4a3425',
        door: '#8b6914',
        accent: '#ffab40',
        ambient: '#1a0f05',
        fog: '#0f0a05',
    },
    ice: {
        name: 'Frozen Fortress',
        floor: '#3a4a5a',
        wall: '#1e2e3e',
        wallTop: '#2a3a4a',
        door: '#5a8aaa',
        accent: '#80d8ff',
        ambient: '#0a1520',
        fog: '#050a10',
    },
};

// Visual config per tile type (used by renderer)
export function getTileVisuals(type, theme = 'dungeon') {
    const palette = THEMES[theme] || THEMES.dungeon;

    const visuals = {
        [TILE_TYPES.EMPTY]: null,
        [TILE_TYPES.FLOOR]: {
            color: palette.floor,
            height: 0.15,
            emissive: '#000000',
            emissiveIntensity: 0,
            opacity: 1,
            metalness: 0.1,
            roughness: 0.9,
        },
        [TILE_TYPES.WALL]: {
            color: palette.wall,
            topColor: palette.wallTop,
            height: 2.2,
            emissive: '#000000',
            emissiveIntensity: 0,
            opacity: 1,
            metalness: 0.2,
            roughness: 0.8,
        },
        [TILE_TYPES.DOOR]: {
            color: palette.door,
            height: 1.8,
            emissive: palette.accent,
            emissiveIntensity: 0.15,
            opacity: 0.9,
            metalness: 0.3,
            roughness: 0.6,
        },
        [TILE_TYPES.WATER]: {
            color: '#1565c0',
            height: 0.08,
            emissive: '#0d47a1',
            emissiveIntensity: 0.3,
            opacity: 0.6,
            metalness: 0.4,
            roughness: 0.1,
        },
        [TILE_TYPES.CHEST]: {
            color: '#ffd54f',
            height: 0.6,
            emissive: '#ff8f00',
            emissiveIntensity: 0.4,
            opacity: 1,
            metalness: 0.6,
            roughness: 0.3,
            floorColor: palette.floor,
        },
        [TILE_TYPES.TORCH]: {
            color: '#ff6d00',
            height: 1.2,
            emissive: '#ff9100',
            emissiveIntensity: 0.8,
            opacity: 1,
            metalness: 0.1,
            roughness: 0.5,
            floorColor: palette.floor,
            isLight: true,
            lightColor: '#ff9100',
            lightIntensity: 5,
            lightDistance: 8,
        },
        [TILE_TYPES.STAIRS]: {
            color: '#78909c',
            height: 0.5,
            emissive: '#455a64',
            emissiveIntensity: 0.1,
            opacity: 1,
            metalness: 0.3,
            roughness: 0.7,
            floorColor: palette.floor,
        },
        [TILE_TYPES.LAVA]: {
            color: '#d84315',
            height: 0.1,
            emissive: '#ff3d00',
            emissiveIntensity: 0.9,
            opacity: 0.85,
            metalness: 0.0,
            roughness: 0.2,
            isLight: true,
            lightColor: '#ff3d00',
            lightIntensity: 3,
            lightDistance: 6,
        },
        [TILE_TYPES.GRASS]: {
            color: '#2e7d32',
            height: 0.18,
            emissive: '#1b5e20',
            emissiveIntensity: 0.05,
            opacity: 1,
            metalness: 0.0,
            roughness: 1.0,
        },
    };

    return visuals[type] || null;
}
